name: General

on:
  push:
    branches: [ master, develop ]
jobs:
  postgres_job:
    name: Postgresql
    runs-on: ubuntu-latest
    steps:
      - name: Starting
        uses: pokemon-tcg-server/postgresql@master
        with:
          branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}