name: General

on:
  push:
    branches: [ master, develop ]
jobs:
  postgres_job:
    name: Postgresql
    runs-on: ubuntu-latest
    steps:
      - name: Starting
        #{owner}/{repo}/{path}/{filename}@{ref}
        uses: pokemon-tcg-server/actions/postgresql@v1
        with:
          branch: master
          username: ${{ inputs.username }}
          token: ${{ secrets.envPAT }}